In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("data/nifty100.db")

companies = pd.read_sql("""
SELECT id, company_name
FROM companies
ORDER BY RANDOM()
LIMIT 5
""", conn)

companies

           id                             company_name
0        NTPC                                 NTPC Ltd
1    HDFCBANK                            HDFC Bank Ltd
2  BAJAJHLDNG          Bajaj Holdings & Investment Ltd
3         PNB                     Punjab National Bank
4   MOTHERSON  Samvardhana Motherson International Ltd

In [2]:
coverage = pd.read_sql("""
SELECT
    company_id,
    COUNT(DISTINCT year) as years_available
FROM profitandloss
GROUP BY company_id
ORDER BY years_available
""", conn)

coverage

    company_id  years_available
0       JIOFIN                3
1         LICI                7
2         ATGL                8
3       ZOMATO                8
4   ADANIGREEN                9
..         ...              ...
95    UNITDSPR               13
96         VBL               13
97        VEDL               13
98       WIPRO               13
99   ZYDUSLIFE               13

[100 rows x 2 columns]

In [3]:
short_history = pd.read_sql("""
SELECT
    company_id,
    COUNT(DISTINCT year) as years_available
FROM profitandloss
GROUP BY company_id
HAVING COUNT(DISTINCT year) < 5
""", conn)

short_history

  company_id  years_available
0     JIOFIN                3

In [4]:
conn.close()